// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.apple.ios.protos.nano;

@SuppressWarnings("hiding")
public interface ColorProto {

  public static final class TypePhotos extends
      com.google.protobuf.nano.MessageNano {

    private static volatile TypePhotos[] _emptyArray;
    public static TypePhotos[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TypePhotos[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string example = 1;
    public String example;

    // optional string type = 2;
    public String type;

    public TypePhotos() {
      clear();
    }

    public TypePhotos clear() {
      example = "";
      type = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.example.equals("")) {
        output.writeString(1, this.example);
      }
      if (!this.type.equals("")) {
        output.writeString(2, this.type);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.example.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.example);
      }
      if (!this.type.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.type);
      }
      return size;
    }

    @Override
    public TypePhotos mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.example = input.readString();
            break;
          }
          case 18: {
            this.type = input.readString();
            break;
          }
        }
      }
    }

    public static TypePhotos parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TypePhotos(), data);
    }

    public static TypePhotos parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TypePhotos().mergeFrom(input);
    }
  }

  public static final class ColorPhotos extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorPhotos[] _emptyArray;
    public static ColorPhotos[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorPhotos[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string example = 1;
    public String example;

    // optional string type = 2;
    public String type;

    // optional string photoName = 3;
    public String photoName;

    // optional string photoUrl = 4;
    public String photoUrl;

    // optional int64 photoId = 5;
    public long photoId;

    public ColorPhotos() {
      clear();
    }

    public ColorPhotos clear() {
      example = "";
      type = "";
      photoName = "";
      photoUrl = "";
      photoId = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.example.equals("")) {
        output.writeString(1, this.example);
      }
      if (!this.type.equals("")) {
        output.writeString(2, this.type);
      }
      if (!this.photoName.equals("")) {
        output.writeString(3, this.photoName);
      }
      if (!this.photoUrl.equals("")) {
        output.writeString(4, this.photoUrl);
      }
      if (this.photoId != 0L) {
        output.writeInt64(5, this.photoId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.example.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.example);
      }
      if (!this.type.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.type);
      }
      if (!this.photoName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.photoName);
      }
      if (!this.photoUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.photoUrl);
      }
      if (this.photoId != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(5, this.photoId);
      }
      return size;
    }

    @Override
    public ColorPhotos mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.example = input.readString();
            break;
          }
          case 18: {
            this.type = input.readString();
            break;
          }
          case 26: {
            this.photoName = input.readString();
            break;
          }
          case 34: {
            this.photoUrl = input.readString();
            break;
          }
          case 40: {
            this.photoId = input.readInt64();
            break;
          }
        }
      }
    }

    public static ColorPhotos parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorPhotos(), data);
    }

    public static ColorPhotos parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorPhotos().mergeFrom(input);
    }
  }

  public static final class ColorPhotosRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorPhotosRequest[] _emptyArray;
    public static ColorPhotosRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorPhotosRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional string idfa = 2;
    public String idfa;

    // optional string bundleId = 3;
    public String bundleId;

    // optional int32 beginPosition = 4;
    public int beginPosition;

    // optional int32 number = 5;
    public int number;

    // optional string listType = 6;
    public String listType;

    // optional string photoType = 7;
    public String photoType;

    public ColorPhotosRequest() {
      clear();
    }

    public ColorPhotosRequest clear() {
      geo = "";
      idfa = "";
      bundleId = "";
      beginPosition = 0;
      number = 0;
      listType = "";
      photoType = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (!this.idfa.equals("")) {
        output.writeString(2, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        output.writeString(3, this.bundleId);
      }
      if (this.beginPosition != 0) {
        output.writeInt32(4, this.beginPosition);
      }
      if (this.number != 0) {
        output.writeInt32(5, this.number);
      }
      if (!this.listType.equals("")) {
        output.writeString(6, this.listType);
      }
      if (!this.photoType.equals("")) {
        output.writeString(7, this.photoType);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (!this.idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.bundleId);
      }
      if (this.beginPosition != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.beginPosition);
      }
      if (this.number != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.number);
      }
      if (!this.listType.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.listType);
      }
      if (!this.photoType.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.photoType);
      }
      return size;
    }

    @Override
    public ColorPhotosRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 18: {
            this.idfa = input.readString();
            break;
          }
          case 26: {
            this.bundleId = input.readString();
            break;
          }
          case 32: {
            this.beginPosition = input.readInt32();
            break;
          }
          case 40: {
            this.number = input.readInt32();
            break;
          }
          case 50: {
            this.listType = input.readString();
            break;
          }
          case 58: {
            this.photoType = input.readString();
            break;
          }
        }
      }
    }

    public static ColorPhotosRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorPhotosRequest(), data);
    }

    public static ColorPhotosRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorPhotosRequest().mergeFrom(input);
    }
  }

  public static final class ColorPhotosResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorPhotosResponse[] _emptyArray;
    public static ColorPhotosResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorPhotosResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .TypePhotos TypePhotosList = 1;
    public TypePhotos[] typePhotosList;

    // repeated .ColorPhotos ColorPhotosList = 2;
    public ColorPhotos[] colorPhotosList;

    // optional string status = 3;
    public String status;

    // optional int64 serverTime = 4;
    public long serverTime;

    public ColorPhotosResponse() {
      clear();
    }

    public ColorPhotosResponse clear() {
      typePhotosList = TypePhotos.emptyArray();
      colorPhotosList = ColorPhotos.emptyArray();
      status = "";
      serverTime = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.typePhotosList != null && this.typePhotosList.length > 0) {
        for (int i = 0; i < this.typePhotosList.length; i++) {
          TypePhotos element = this.typePhotosList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.colorPhotosList != null && this.colorPhotosList.length > 0) {
        for (int i = 0; i < this.colorPhotosList.length; i++) {
          ColorPhotos element = this.colorPhotosList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (!this.status.equals("")) {
        output.writeString(3, this.status);
      }
      if (this.serverTime != 0L) {
        output.writeInt64(4, this.serverTime);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.typePhotosList != null && this.typePhotosList.length > 0) {
        for (int i = 0; i < this.typePhotosList.length; i++) {
          TypePhotos element = this.typePhotosList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.colorPhotosList != null && this.colorPhotosList.length > 0) {
        for (int i = 0; i < this.colorPhotosList.length; i++) {
          ColorPhotos element = this.colorPhotosList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (!this.status.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.status);
      }
      if (this.serverTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.serverTime);
      }
      return size;
    }

    @Override
    public ColorPhotosResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.typePhotosList == null ? 0 : this.typePhotosList.length;
            TypePhotos[] newArray =
                new TypePhotos[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.typePhotosList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new TypePhotos();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new TypePhotos();
            input.readMessage(newArray[i]);
            this.typePhotosList = newArray;
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.colorPhotosList == null ? 0 : this.colorPhotosList.length;
            ColorPhotos[] newArray =
                new ColorPhotos[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.colorPhotosList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new ColorPhotos();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new ColorPhotos();
            input.readMessage(newArray[i]);
            this.colorPhotosList = newArray;
            break;
          }
          case 26: {
            this.status = input.readString();
            break;
          }
          case 32: {
            this.serverTime = input.readInt64();
            break;
          }
        }
      }
    }

    public static ColorPhotosResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorPhotosResponse(), data);
    }

    public static ColorPhotosResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorPhotosResponse().mergeFrom(input);
    }
  }

  public static final class AdStrategy extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdStrategy[] _emptyArray;
    public static AdStrategy[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdStrategy[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 adType = 1;
    public int adType;

    // optional int32 adSource = 2;
    public int adSource;

    // optional int32 priority = 3;
    public int priority;

    // optional string adID = 4;
    public String adID;

    // optional int32 positionID = 5;
    public int positionID;

    // optional int32 adreward = 6;
    public int adreward;

    public AdStrategy() {
      clear();
    }

    public AdStrategy clear() {
      adType = 0;
      adSource = 0;
      priority = 0;
      adID = "";
      positionID = 0;
      adreward = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.adType != 0) {
        output.writeInt32(1, this.adType);
      }
      if (this.adSource != 0) {
        output.writeInt32(2, this.adSource);
      }
      if (this.priority != 0) {
        output.writeInt32(3, this.priority);
      }
      if (!this.adID.equals("")) {
        output.writeString(4, this.adID);
      }
      if (this.positionID != 0) {
        output.writeInt32(5, this.positionID);
      }
      if (this.adreward != 0) {
        output.writeInt32(6, this.adreward);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.adType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.adType);
      }
      if (this.adSource != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.adSource);
      }
      if (this.priority != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.priority);
      }
      if (!this.adID.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.adID);
      }
      if (this.positionID != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.positionID);
      }
      if (this.adreward != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.adreward);
      }
      return size;
    }

    @Override
    public AdStrategy mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.adType = input.readInt32();
            break;
          }
          case 16: {
            this.adSource = input.readInt32();
            break;
          }
          case 24: {
            this.priority = input.readInt32();
            break;
          }
          case 34: {
            this.adID = input.readString();
            break;
          }
          case 40: {
            this.positionID = input.readInt32();
            break;
          }
          case 48: {
            this.adreward = input.readInt32();
            break;
          }
        }
      }
    }

    public static AdStrategy parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdStrategy(), data);
    }

    public static AdStrategy parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdStrategy().mergeFrom(input);
    }
  }

  public static final class AdControl extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdControl[] _emptyArray;
    public static AdControl[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdControl[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 init = 1;
    public int init;

    // optional int32 show = 2;
    public int show;

    // optional int32 positionID = 3;
    public int positionID;

    // optional int32 requestIntervalTime = 4;
    public int requestIntervalTime;

    // optional int32 status = 5;
    public int status;

    public AdControl() {
      clear();
    }

    public AdControl clear() {
      init = 0;
      show = 0;
      positionID = 0;
      requestIntervalTime = 0;
      status = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.init != 0) {
        output.writeInt32(1, this.init);
      }
      if (this.show != 0) {
        output.writeInt32(2, this.show);
      }
      if (this.positionID != 0) {
        output.writeInt32(3, this.positionID);
      }
      if (this.requestIntervalTime != 0) {
        output.writeInt32(4, this.requestIntervalTime);
      }
      if (this.status != 0) {
        output.writeInt32(5, this.status);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.init != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.init);
      }
      if (this.show != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.show);
      }
      if (this.positionID != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.positionID);
      }
      if (this.requestIntervalTime != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.requestIntervalTime);
      }
      if (this.status != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.status);
      }
      return size;
    }

    @Override
    public AdControl mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.init = input.readInt32();
            break;
          }
          case 16: {
            this.show = input.readInt32();
            break;
          }
          case 24: {
            this.positionID = input.readInt32();
            break;
          }
          case 32: {
            this.requestIntervalTime = input.readInt32();
            break;
          }
          case 40: {
            this.status = input.readInt32();
            break;
          }
        }
      }
    }

    public static AdControl parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdControl(), data);
    }

    public static AdControl parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdControl().mergeFrom(input);
    }
  }

  public static final class AdClick extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdClick[] _emptyArray;
    public static AdClick[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdClick[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 positionID = 1;
    public int positionID;

    // optional string minClick = 2;
    public String minClick;

    // optional string maxClick = 3;
    public String maxClick;

    public AdClick() {
      clear();
    }

    public AdClick clear() {
      positionID = 0;
      minClick = "";
      maxClick = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.positionID != 0) {
        output.writeInt32(1, this.positionID);
      }
      if (!this.minClick.equals("")) {
        output.writeString(2, this.minClick);
      }
      if (!this.maxClick.equals("")) {
        output.writeString(3, this.maxClick);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.positionID != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.positionID);
      }
      if (!this.minClick.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.minClick);
      }
      if (!this.maxClick.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.maxClick);
      }
      return size;
    }

    @Override
    public AdClick mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.positionID = input.readInt32();
            break;
          }
          case 18: {
            this.minClick = input.readString();
            break;
          }
          case 26: {
            this.maxClick = input.readString();
            break;
          }
        }
      }
    }

    public static AdClick parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdClick(), data);
    }

    public static AdClick parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdClick().mergeFrom(input);
    }
  }

  public static final class AdResources extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdResources[] _emptyArray;
    public static AdResources[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdResources[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string sourceKey = 1;
    public String sourceKey;

    // optional string typeKey = 2;
    public String typeKey;

    // optional string type = 3;
    public String type;

    public AdResources() {
      clear();
    }

    public AdResources clear() {
      sourceKey = "";
      typeKey = "";
      type = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.sourceKey.equals("")) {
        output.writeString(1, this.sourceKey);
      }
      if (!this.typeKey.equals("")) {
        output.writeString(2, this.typeKey);
      }
      if (!this.type.equals("")) {
        output.writeString(3, this.type);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.sourceKey.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.sourceKey);
      }
      if (!this.typeKey.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.typeKey);
      }
      if (!this.type.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.type);
      }
      return size;
    }

    @Override
    public AdResources mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.sourceKey = input.readString();
            break;
          }
          case 18: {
            this.typeKey = input.readString();
            break;
          }
          case 26: {
            this.type = input.readString();
            break;
          }
        }
      }
    }

    public static AdResources parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdResources(), data);
    }

    public static AdResources parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdResources().mergeFrom(input);
    }
  }

  public static final class ColorRegistrationRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorRegistrationRequest[] _emptyArray;
    public static ColorRegistrationRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorRegistrationRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional string os = 2;
    public String os;

    // optional string idfa = 3;
    public String idfa;

    // optional string bundleId = 4;
    public String bundleId;

    // optional string bundleDisplayName = 5;
    public String bundleDisplayName;

    // optional string build = 6;
    public String build;

    // optional string version = 7;
    public String version;

    public ColorRegistrationRequest() {
      clear();
    }

    public ColorRegistrationRequest clear() {
      geo = "";
      os = "";
      idfa = "";
      bundleId = "";
      bundleDisplayName = "";
      build = "";
      version = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (!this.os.equals("")) {
        output.writeString(2, this.os);
      }
      if (!this.idfa.equals("")) {
        output.writeString(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        output.writeString(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        output.writeString(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        output.writeString(6, this.build);
      }
      if (!this.version.equals("")) {
        output.writeString(7, this.version);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (!this.os.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.os);
      }
      if (!this.idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.build);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.version);
      }
      return size;
    }

    @Override
    public ColorRegistrationRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 18: {
            this.os = input.readString();
            break;
          }
          case 26: {
            this.idfa = input.readString();
            break;
          }
          case 34: {
            this.bundleId = input.readString();
            break;
          }
          case 42: {
            this.bundleDisplayName = input.readString();
            break;
          }
          case 50: {
            this.build = input.readString();
            break;
          }
          case 58: {
            this.version = input.readString();
            break;
          }
        }
      }
    }

    public static ColorRegistrationRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorRegistrationRequest(), data);
    }

    public static ColorRegistrationRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorRegistrationRequest().mergeFrom(input);
    }
  }

  public static final class ColorRegistrationResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorRegistrationResponse[] _emptyArray;
    public static ColorRegistrationResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorRegistrationResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 timeStamp = 1;
    public long timeStamp;

    // optional string userId = 2;
    public String userId;

    public ColorRegistrationResponse() {
      clear();
    }

    public ColorRegistrationResponse clear() {
      timeStamp = 0L;
      userId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.timeStamp != 0L) {
        output.writeInt64(1, this.timeStamp);
      }
      if (!this.userId.equals("")) {
        output.writeString(2, this.userId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.timeStamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.timeStamp);
      }
      if (!this.userId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.userId);
      }
      return size;
    }

    @Override
    public ColorRegistrationResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.timeStamp = input.readInt64();
            break;
          }
          case 18: {
            this.userId = input.readString();
            break;
          }
        }
      }
    }

    public static ColorRegistrationResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorRegistrationResponse(), data);
    }

    public static ColorRegistrationResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorRegistrationResponse().mergeFrom(input);
    }
  }

  public static final class ColorStrategyRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorStrategyRequest[] _emptyArray;
    public static ColorStrategyRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorStrategyRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 timeStamp = 1;
    public long timeStamp;

    // optional string geo = 2;
    public String geo;

    // optional string idfa = 3;
    public String idfa;

    // optional string bundleId = 4;
    public String bundleId;

    // optional string bundleDisplayName = 5;
    public String bundleDisplayName;

    // optional string build = 6;
    public String build;

    // optional string version = 7;
    public String version;

    public ColorStrategyRequest() {
      clear();
    }

    public ColorStrategyRequest clear() {
      timeStamp = 0L;
      geo = "";
      idfa = "";
      bundleId = "";
      bundleDisplayName = "";
      build = "";
      version = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.timeStamp != 0L) {
        output.writeInt64(1, this.timeStamp);
      }
      if (!this.geo.equals("")) {
        output.writeString(2, this.geo);
      }
      if (!this.idfa.equals("")) {
        output.writeString(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        output.writeString(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        output.writeString(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        output.writeString(6, this.build);
      }
      if (!this.version.equals("")) {
        output.writeString(7, this.version);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.timeStamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.timeStamp);
      }
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.geo);
      }
      if (!this.idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.build);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.version);
      }
      return size;
    }

    @Override
    public ColorStrategyRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.timeStamp = input.readInt64();
            break;
          }
          case 18: {
            this.geo = input.readString();
            break;
          }
          case 26: {
            this.idfa = input.readString();
            break;
          }
          case 34: {
            this.bundleId = input.readString();
            break;
          }
          case 42: {
            this.bundleDisplayName = input.readString();
            break;
          }
          case 50: {
            this.build = input.readString();
            break;
          }
          case 58: {
            this.version = input.readString();
            break;
          }
        }
      }
    }

    public static ColorStrategyRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorStrategyRequest(), data);
    }

    public static ColorStrategyRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorStrategyRequest().mergeFrom(input);
    }
  }

  public static final class ColorStrategyResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorStrategyResponse[] _emptyArray;
    public static ColorStrategyResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorStrategyResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .AdStrategy adStrategyList = 1;
    public AdStrategy[] adStrategyList;

    // repeated .AdControl adControlList = 2;
    public AdControl[] adControlList;

    // repeated .AdClick adClickList = 3;
    public AdClick[] adClickList;

    // repeated .AdResources adResourcesList = 4;
    public AdResources[] adResourcesList;

    // optional int64 serverTime = 5;
    public long serverTime;

    public ColorStrategyResponse() {
      clear();
    }

    public ColorStrategyResponse clear() {
      adStrategyList = AdStrategy.emptyArray();
      adControlList = AdControl.emptyArray();
      adClickList = AdClick.emptyArray();
      adResourcesList = AdResources.emptyArray();
      serverTime = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.adStrategyList != null && this.adStrategyList.length > 0) {
        for (int i = 0; i < this.adStrategyList.length; i++) {
          AdStrategy element = this.adStrategyList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.adControlList != null && this.adControlList.length > 0) {
        for (int i = 0; i < this.adControlList.length; i++) {
          AdControl element = this.adControlList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.adClickList != null && this.adClickList.length > 0) {
        for (int i = 0; i < this.adClickList.length; i++) {
          AdClick element = this.adClickList[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      if (this.adResourcesList != null && this.adResourcesList.length > 0) {
        for (int i = 0; i < this.adResourcesList.length; i++) {
          AdResources element = this.adResourcesList[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      if (this.serverTime != 0L) {
        output.writeInt64(5, this.serverTime);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.adStrategyList != null && this.adStrategyList.length > 0) {
        for (int i = 0; i < this.adStrategyList.length; i++) {
          AdStrategy element = this.adStrategyList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.adControlList != null && this.adControlList.length > 0) {
        for (int i = 0; i < this.adControlList.length; i++) {
          AdControl element = this.adControlList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.adClickList != null && this.adClickList.length > 0) {
        for (int i = 0; i < this.adClickList.length; i++) {
          AdClick element = this.adClickList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      if (this.adResourcesList != null && this.adResourcesList.length > 0) {
        for (int i = 0; i < this.adResourcesList.length; i++) {
          AdResources element = this.adResourcesList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      if (this.serverTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(5, this.serverTime);
      }
      return size;
    }

    @Override
    public ColorStrategyResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.adStrategyList == null ? 0 : this.adStrategyList.length;
            AdStrategy[] newArray =
                new AdStrategy[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adStrategyList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new AdStrategy();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new AdStrategy();
            input.readMessage(newArray[i]);
            this.adStrategyList = newArray;
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.adControlList == null ? 0 : this.adControlList.length;
            AdControl[] newArray =
                new AdControl[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adControlList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new AdControl();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new AdControl();
            input.readMessage(newArray[i]);
            this.adControlList = newArray;
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.adClickList == null ? 0 : this.adClickList.length;
            AdClick[] newArray =
                new AdClick[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adClickList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new AdClick();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new AdClick();
            input.readMessage(newArray[i]);
            this.adClickList = newArray;
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.adResourcesList == null ? 0 : this.adResourcesList.length;
            AdResources[] newArray =
                new AdResources[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adResourcesList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new AdResources();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new AdResources();
            input.readMessage(newArray[i]);
            this.adResourcesList = newArray;
            break;
          }
          case 40: {
            this.serverTime = input.readInt64();
            break;
          }
        }
      }
    }

    public static ColorStrategyResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorStrategyResponse(), data);
    }

    public static ColorStrategyResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorStrategyResponse().mergeFrom(input);
    }
  }

  public static final class ColorDataRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorDataRequest[] _emptyArray;
    public static ColorDataRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorDataRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional string bundleId = 2;
    public String bundleId;

    // optional string bundleDisplayName = 3;
    public String bundleDisplayName;

    // optional string build = 4;
    public String build;

    // optional string version = 5;
    public String version;

    // optional string networkType = 6;
    public String networkType;

    // optional string idfa = 7;
    public String idfa;

    // optional int32 eventNumber = 8;
    public int eventNumber;

    // repeated .eventApplicationStartup applicationStartupList = 9;
    public eventApplicationStartup[] applicationStartupList;

    // repeated .eventPageSwitching pageSwitchingList = 10;
    public eventPageSwitching[] pageSwitchingList;

    // repeated .eventAdRequest adRequestList = 11;
    public eventAdRequest[] adRequestList;

    // repeated .eventAdShow adShowList = 12;
    public eventAdShow[] adShowList;

    // repeated .eventAdClick adClickList = 13;
    public eventAdClick[] adClickList;

    // optional int64 timeStamp = 14;
    public long timeStamp;

    public ColorDataRequest() {
      clear();
    }

    public ColorDataRequest clear() {
      geo = "";
      bundleId = "";
      bundleDisplayName = "";
      build = "";
      version = "";
      networkType = "";
      idfa = "";
      eventNumber = 0;
      applicationStartupList = eventApplicationStartup.emptyArray();
      pageSwitchingList = eventPageSwitching.emptyArray();
      adRequestList = eventAdRequest.emptyArray();
      adShowList = eventAdShow.emptyArray();
      adClickList = eventAdClick.emptyArray();
      timeStamp = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (!this.bundleId.equals("")) {
        output.writeString(2, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        output.writeString(3, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        output.writeString(4, this.build);
      }
      if (!this.version.equals("")) {
        output.writeString(5, this.version);
      }
      if (!this.networkType.equals("")) {
        output.writeString(6, this.networkType);
      }
      if (!this.idfa.equals("")) {
        output.writeString(7, this.idfa);
      }
      if (this.eventNumber != 0) {
        output.writeInt32(8, this.eventNumber);
      }
      if (this.applicationStartupList != null && this.applicationStartupList.length > 0) {
        for (int i = 0; i < this.applicationStartupList.length; i++) {
          eventApplicationStartup element = this.applicationStartupList[i];
          if (element != null) {
            output.writeMessage(9, element);
          }
        }
      }
      if (this.pageSwitchingList != null && this.pageSwitchingList.length > 0) {
        for (int i = 0; i < this.pageSwitchingList.length; i++) {
          eventPageSwitching element = this.pageSwitchingList[i];
          if (element != null) {
            output.writeMessage(10, element);
          }
        }
      }
      if (this.adRequestList != null && this.adRequestList.length > 0) {
        for (int i = 0; i < this.adRequestList.length; i++) {
          eventAdRequest element = this.adRequestList[i];
          if (element != null) {
            output.writeMessage(11, element);
          }
        }
      }
      if (this.adShowList != null && this.adShowList.length > 0) {
        for (int i = 0; i < this.adShowList.length; i++) {
          eventAdShow element = this.adShowList[i];
          if (element != null) {
            output.writeMessage(12, element);
          }
        }
      }
      if (this.adClickList != null && this.adClickList.length > 0) {
        for (int i = 0; i < this.adClickList.length; i++) {
          eventAdClick element = this.adClickList[i];
          if (element != null) {
            output.writeMessage(13, element);
          }
        }
      }
      if (this.timeStamp != 0L) {
        output.writeInt64(14, this.timeStamp);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.build);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.version);
      }
      if (!this.networkType.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.networkType);
      }
      if (!this.idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.idfa);
      }
      if (this.eventNumber != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(8, this.eventNumber);
      }
      if (this.applicationStartupList != null && this.applicationStartupList.length > 0) {
        for (int i = 0; i < this.applicationStartupList.length; i++) {
          eventApplicationStartup element = this.applicationStartupList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(9, element);
          }
        }
      }
      if (this.pageSwitchingList != null && this.pageSwitchingList.length > 0) {
        for (int i = 0; i < this.pageSwitchingList.length; i++) {
          eventPageSwitching element = this.pageSwitchingList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(10, element);
          }
        }
      }
      if (this.adRequestList != null && this.adRequestList.length > 0) {
        for (int i = 0; i < this.adRequestList.length; i++) {
          eventAdRequest element = this.adRequestList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(11, element);
          }
        }
      }
      if (this.adShowList != null && this.adShowList.length > 0) {
        for (int i = 0; i < this.adShowList.length; i++) {
          eventAdShow element = this.adShowList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(12, element);
          }
        }
      }
      if (this.adClickList != null && this.adClickList.length > 0) {
        for (int i = 0; i < this.adClickList.length; i++) {
          eventAdClick element = this.adClickList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(13, element);
          }
        }
      }
      if (this.timeStamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(14, this.timeStamp);
      }
      return size;
    }

    @Override
    public ColorDataRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 18: {
            this.bundleId = input.readString();
            break;
          }
          case 26: {
            this.bundleDisplayName = input.readString();
            break;
          }
          case 34: {
            this.build = input.readString();
            break;
          }
          case 42: {
            this.version = input.readString();
            break;
          }
          case 50: {
            this.networkType = input.readString();
            break;
          }
          case 58: {
            this.idfa = input.readString();
            break;
          }
          case 64: {
            this.eventNumber = input.readInt32();
            break;
          }
          case 74: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 74);
            int i = this.applicationStartupList == null ? 0 : this.applicationStartupList.length;
            eventApplicationStartup[] newArray =
                new eventApplicationStartup[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.applicationStartupList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new eventApplicationStartup();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new eventApplicationStartup();
            input.readMessage(newArray[i]);
            this.applicationStartupList = newArray;
            break;
          }
          case 82: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 82);
            int i = this.pageSwitchingList == null ? 0 : this.pageSwitchingList.length;
            eventPageSwitching[] newArray =
                new eventPageSwitching[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.pageSwitchingList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new eventPageSwitching();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new eventPageSwitching();
            input.readMessage(newArray[i]);
            this.pageSwitchingList = newArray;
            break;
          }
          case 90: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 90);
            int i = this.adRequestList == null ? 0 : this.adRequestList.length;
            eventAdRequest[] newArray =
                new eventAdRequest[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adRequestList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new eventAdRequest();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new eventAdRequest();
            input.readMessage(newArray[i]);
            this.adRequestList = newArray;
            break;
          }
          case 98: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 98);
            int i = this.adShowList == null ? 0 : this.adShowList.length;
            eventAdShow[] newArray =
                new eventAdShow[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adShowList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new eventAdShow();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new eventAdShow();
            input.readMessage(newArray[i]);
            this.adShowList = newArray;
            break;
          }
          case 106: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 106);
            int i = this.adClickList == null ? 0 : this.adClickList.length;
            eventAdClick[] newArray =
                new eventAdClick[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adClickList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new eventAdClick();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new eventAdClick();
            input.readMessage(newArray[i]);
            this.adClickList = newArray;
            break;
          }
          case 112: {
            this.timeStamp = input.readInt64();
            break;
          }
        }
      }
    }

    public static ColorDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorDataRequest(), data);
    }

    public static ColorDataRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorDataRequest().mergeFrom(input);
    }
  }

  public static final class ColorDataResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorDataResponse[] _emptyArray;
    public static ColorDataResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorDataResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string success = 1;
    public String success;

    // optional bool status = 2;
    public boolean status;

    public ColorDataResponse() {
      clear();
    }

    public ColorDataResponse clear() {
      success = "";
      status = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.success.equals("")) {
        output.writeString(1, this.success);
      }
      if (this.status != false) {
        output.writeBool(2, this.status);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.success.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.success);
      }
      if (this.status != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.status);
      }
      return size;
    }

    @Override
    public ColorDataResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.success = input.readString();
            break;
          }
          case 16: {
            this.status = input.readBool();
            break;
          }
        }
      }
    }

    public static ColorDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorDataResponse(), data);
    }

    public static ColorDataResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorDataResponse().mergeFrom(input);
    }
  }

  public static final class eventApplicationStartup extends
      com.google.protobuf.nano.MessageNano {

    private static volatile eventApplicationStartup[] _emptyArray;
    public static eventApplicationStartup[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new eventApplicationStartup[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional int64 timeStartup = 2;
    public long timeStartup;

    public eventApplicationStartup() {
      clear();
    }

    public eventApplicationStartup clear() {
      geo = "";
      timeStartup = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (this.timeStartup != 0L) {
        output.writeInt64(2, this.timeStartup);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (this.timeStartup != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.timeStartup);
      }
      return size;
    }

    @Override
    public eventApplicationStartup mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 16: {
            this.timeStartup = input.readInt64();
            break;
          }
        }
      }
    }

    public static eventApplicationStartup parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new eventApplicationStartup(), data);
    }

    public static eventApplicationStartup parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new eventApplicationStartup().mergeFrom(input);
    }
  }

  public static final class eventPageSwitching extends
      com.google.protobuf.nano.MessageNano {

    private static volatile eventPageSwitching[] _emptyArray;
    public static eventPageSwitching[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new eventPageSwitching[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string pageName = 1;
    public String pageName;

    // optional string geo = 2;
    public String geo;

    // optional int64 timeSwitching = 3;
    public long timeSwitching;

    public eventPageSwitching() {
      clear();
    }

    public eventPageSwitching clear() {
      pageName = "";
      geo = "";
      timeSwitching = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.pageName.equals("")) {
        output.writeString(1, this.pageName);
      }
      if (!this.geo.equals("")) {
        output.writeString(2, this.geo);
      }
      if (this.timeSwitching != 0L) {
        output.writeInt64(3, this.timeSwitching);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.pageName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.pageName);
      }
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.geo);
      }
      if (this.timeSwitching != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.timeSwitching);
      }
      return size;
    }

    @Override
    public eventPageSwitching mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.pageName = input.readString();
            break;
          }
          case 18: {
            this.geo = input.readString();
            break;
          }
          case 24: {
            this.timeSwitching = input.readInt64();
            break;
          }
        }
      }
    }

    public static eventPageSwitching parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new eventPageSwitching(), data);
    }

    public static eventPageSwitching parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new eventPageSwitching().mergeFrom(input);
    }
  }

  public static final class eventAdRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile eventAdRequest[] _emptyArray;
    public static eventAdRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new eventAdRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional int64 timeRequest = 2;
    public long timeRequest;

    // optional int32 adPositionNumber = 3;
    public int adPositionNumber;

    // optional int32 adType = 4;
    public int adType;

    public eventAdRequest() {
      clear();
    }

    public eventAdRequest clear() {
      geo = "";
      timeRequest = 0L;
      adPositionNumber = 0;
      adType = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (this.timeRequest != 0L) {
        output.writeInt64(2, this.timeRequest);
      }
      if (this.adPositionNumber != 0) {
        output.writeInt32(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        output.writeInt32(4, this.adType);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (this.timeRequest != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.timeRequest);
      }
      if (this.adPositionNumber != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.adType);
      }
      return size;
    }

    @Override
    public eventAdRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 16: {
            this.timeRequest = input.readInt64();
            break;
          }
          case 24: {
            this.adPositionNumber = input.readInt32();
            break;
          }
          case 32: {
            this.adType = input.readInt32();
            break;
          }
        }
      }
    }

    public static eventAdRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new eventAdRequest(), data);
    }

    public static eventAdRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new eventAdRequest().mergeFrom(input);
    }
  }

  public static final class eventAdShow extends
      com.google.protobuf.nano.MessageNano {

    private static volatile eventAdShow[] _emptyArray;
    public static eventAdShow[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new eventAdShow[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional int64 timeShow = 2;
    public long timeShow;

    // optional int32 adPositionNumber = 3;
    public int adPositionNumber;

    // optional int32 adType = 4;
    public int adType;

    public eventAdShow() {
      clear();
    }

    public eventAdShow clear() {
      geo = "";
      timeShow = 0L;
      adPositionNumber = 0;
      adType = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (this.timeShow != 0L) {
        output.writeInt64(2, this.timeShow);
      }
      if (this.adPositionNumber != 0) {
        output.writeInt32(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        output.writeInt32(4, this.adType);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (this.timeShow != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.timeShow);
      }
      if (this.adPositionNumber != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.adType);
      }
      return size;
    }

    @Override
    public eventAdShow mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 16: {
            this.timeShow = input.readInt64();
            break;
          }
          case 24: {
            this.adPositionNumber = input.readInt32();
            break;
          }
          case 32: {
            this.adType = input.readInt32();
            break;
          }
        }
      }
    }

    public static eventAdShow parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new eventAdShow(), data);
    }

    public static eventAdShow parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new eventAdShow().mergeFrom(input);
    }
  }

  public static final class eventAdClick extends
      com.google.protobuf.nano.MessageNano {

    private static volatile eventAdClick[] _emptyArray;
    public static eventAdClick[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new eventAdClick[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional int64 timeClick = 2;
    public long timeClick;

    // optional int32 adPositionNumber = 3;
    public int adPositionNumber;

    // optional int32 adType = 4;
    public int adType;

    public eventAdClick() {
      clear();
    }

    public eventAdClick clear() {
      geo = "";
      timeClick = 0L;
      adPositionNumber = 0;
      adType = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (this.timeClick != 0L) {
        output.writeInt64(2, this.timeClick);
      }
      if (this.adPositionNumber != 0) {
        output.writeInt32(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        output.writeInt32(4, this.adType);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (this.timeClick != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.timeClick);
      }
      if (this.adPositionNumber != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.adType);
      }
      return size;
    }

    @Override
    public eventAdClick mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 16: {
            this.timeClick = input.readInt64();
            break;
          }
          case 24: {
            this.adPositionNumber = input.readInt32();
            break;
          }
          case 32: {
            this.adType = input.readInt32();
            break;
          }
        }
      }
    }

    public static eventAdClick parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new eventAdClick(), data);
    }

    public static eventAdClick parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new eventAdClick().mergeFrom(input);
    }
  }

  public static final class ColorSendPushRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorSendPushRequest[] _emptyArray;
    public static ColorSendPushRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorSendPushRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 timeStamp = 1;
    public long timeStamp;

    // optional string geo = 2;
    public String geo;

    // optional string idfa = 3;
    public String idfa;

    // optional string bundleId = 4;
    public String bundleId;

    // optional string bundleDisplayName = 5;
    public String bundleDisplayName;

    // optional string build = 6;
    public String build;

    // optional string version = 7;
    public String version;

    // optional string deviceToken = 8;
    public String deviceToken;

    // optional int32 isUninstall = 9;
    public int isUninstall;

    public ColorSendPushRequest() {
      clear();
    }

    public ColorSendPushRequest clear() {
      timeStamp = 0L;
      geo = "";
      idfa = "";
      bundleId = "";
      bundleDisplayName = "";
      build = "";
      version = "";
      deviceToken = "";
      isUninstall = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.timeStamp != 0L) {
        output.writeInt64(1, this.timeStamp);
      }
      if (!this.geo.equals("")) {
        output.writeString(2, this.geo);
      }
      if (!this.idfa.equals("")) {
        output.writeString(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        output.writeString(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        output.writeString(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        output.writeString(6, this.build);
      }
      if (!this.version.equals("")) {
        output.writeString(7, this.version);
      }
      if (!this.deviceToken.equals("")) {
        output.writeString(8, this.deviceToken);
      }
      if (this.isUninstall != 0) {
        output.writeInt32(9, this.isUninstall);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.timeStamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.timeStamp);
      }
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.geo);
      }
      if (!this.idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.build);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.version);
      }
      if (!this.deviceToken.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.deviceToken);
      }
      if (this.isUninstall != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.isUninstall);
      }
      return size;
    }

    @Override
    public ColorSendPushRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.timeStamp = input.readInt64();
            break;
          }
          case 18: {
            this.geo = input.readString();
            break;
          }
          case 26: {
            this.idfa = input.readString();
            break;
          }
          case 34: {
            this.bundleId = input.readString();
            break;
          }
          case 42: {
            this.bundleDisplayName = input.readString();
            break;
          }
          case 50: {
            this.build = input.readString();
            break;
          }
          case 58: {
            this.version = input.readString();
            break;
          }
          case 66: {
            this.deviceToken = input.readString();
            break;
          }
          case 72: {
            this.isUninstall = input.readInt32();
            break;
          }
        }
      }
    }

    public static ColorSendPushRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorSendPushRequest(), data);
    }

    public static ColorSendPushRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorSendPushRequest().mergeFrom(input);
    }
  }

  public static final class ColorSendPushResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ColorSendPushResponse[] _emptyArray;
    public static ColorSendPushResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ColorSendPushResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 sendTime = 1;
    public long sendTime;

    // optional string success = 2;
    public String success;

    public ColorSendPushResponse() {
      clear();
    }

    public ColorSendPushResponse clear() {
      sendTime = 0L;
      success = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.sendTime != 0L) {
        output.writeInt64(1, this.sendTime);
      }
      if (!this.success.equals("")) {
        output.writeString(2, this.success);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.sendTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.sendTime);
      }
      if (!this.success.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.success);
      }
      return size;
    }

    @Override
    public ColorSendPushResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.sendTime = input.readInt64();
            break;
          }
          case 18: {
            this.success = input.readString();
            break;
          }
        }
      }
    }

    public static ColorSendPushResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ColorSendPushResponse(), data);
    }

    public static ColorSendPushResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ColorSendPushResponse().mergeFrom(input);
    }
  }
}
