// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.apple.ios.protos.nano;

@SuppressWarnings("hiding")
public interface DataProto {

  public static final class AdStrategy extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdStrategy[] _emptyArray;
    public static AdStrategy[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdStrategy[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 adType = 1;
    public int adType;

    // optional int32 adSource = 2;
    public int adSource;

    // optional int32 priority = 3;
    public int priority;

    // optional string adID = 4;
    public String adID;

    // optional int32 positionID = 5;
    public int positionID;

    // optional int32 adreward = 6;
    public int adreward;

    public AdStrategy() {
      clear();
    }

    public AdStrategy clear() {
      adType = 0;
      adSource = 0;
      priority = 0;
      adID = "";
      positionID = 0;
      adreward = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.adType != 0) {
        output.writeInt32(1, this.adType);
      }
      if (this.adSource != 0) {
        output.writeInt32(2, this.adSource);
      }
      if (this.priority != 0) {
        output.writeInt32(3, this.priority);
      }
      if (!this.adID.equals("")) {
        output.writeString(4, this.adID);
      }
      if (this.positionID != 0) {
        output.writeInt32(5, this.positionID);
      }
      if (this.adreward != 0) {
        output.writeInt32(6, this.adreward);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.adType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.adType);
      }
      if (this.adSource != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.adSource);
      }
      if (this.priority != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.priority);
      }
      if (!this.adID.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.adID);
      }
      if (this.positionID != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.positionID);
      }
      if (this.adreward != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.adreward);
      }
      return size;
    }

    @Override
    public AdStrategy mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.adType = input.readInt32();
            break;
          }
          case 16: {
            this.adSource = input.readInt32();
            break;
          }
          case 24: {
            this.priority = input.readInt32();
            break;
          }
          case 34: {
            this.adID = input.readString();
            break;
          }
          case 40: {
            this.positionID = input.readInt32();
            break;
          }
          case 48: {
            this.adreward = input.readInt32();
            break;
          }
        }
      }
    }

    public static AdStrategy parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdStrategy(), data);
    }

    public static AdStrategy parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdStrategy().mergeFrom(input);
    }
  }

  public static final class AdControl extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdControl[] _emptyArray;
    public static AdControl[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdControl[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 init = 1;
    public int init;

    // optional int32 show = 2;
    public int show;

    // optional int32 positionID = 3;
    public int positionID;

    // optional int32 requestIntervalTime = 4;
    public int requestIntervalTime;

    // optional int32 status = 5;
    public int status;

    public AdControl() {
      clear();
    }

    public AdControl clear() {
      init = 0;
      show = 0;
      positionID = 0;
      requestIntervalTime = 0;
      status = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.init != 0) {
        output.writeInt32(1, this.init);
      }
      if (this.show != 0) {
        output.writeInt32(2, this.show);
      }
      if (this.positionID != 0) {
        output.writeInt32(3, this.positionID);
      }
      if (this.requestIntervalTime != 0) {
        output.writeInt32(4, this.requestIntervalTime);
      }
      if (this.status != 0) {
        output.writeInt32(5, this.status);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.init != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.init);
      }
      if (this.show != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.show);
      }
      if (this.positionID != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.positionID);
      }
      if (this.requestIntervalTime != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.requestIntervalTime);
      }
      if (this.status != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.status);
      }
      return size;
    }

    @Override
    public AdControl mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.init = input.readInt32();
            break;
          }
          case 16: {
            this.show = input.readInt32();
            break;
          }
          case 24: {
            this.positionID = input.readInt32();
            break;
          }
          case 32: {
            this.requestIntervalTime = input.readInt32();
            break;
          }
          case 40: {
            this.status = input.readInt32();
            break;
          }
        }
      }
    }

    public static AdControl parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdControl(), data);
    }

    public static AdControl parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdControl().mergeFrom(input);
    }
  }

  public static final class AdClick extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdClick[] _emptyArray;
    public static AdClick[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdClick[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 positionID = 1;
    public int positionID;

    // optional string minClick = 2;
    public String minClick;

    // optional string maxClick = 3;
    public String maxClick;

    public AdClick() {
      clear();
    }

    public AdClick clear() {
      positionID = 0;
      minClick = "";
      maxClick = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.positionID != 0) {
        output.writeInt32(1, this.positionID);
      }
      if (!this.minClick.equals("")) {
        output.writeString(2, this.minClick);
      }
      if (!this.maxClick.equals("")) {
        output.writeString(3, this.maxClick);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.positionID != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.positionID);
      }
      if (!this.minClick.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.minClick);
      }
      if (!this.maxClick.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.maxClick);
      }
      return size;
    }

    @Override
    public AdClick mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.positionID = input.readInt32();
            break;
          }
          case 18: {
            this.minClick = input.readString();
            break;
          }
          case 26: {
            this.maxClick = input.readString();
            break;
          }
        }
      }
    }

    public static AdClick parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdClick(), data);
    }

    public static AdClick parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdClick().mergeFrom(input);
    }
  }

  public static final class AdResources extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdResources[] _emptyArray;
    public static AdResources[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdResources[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string soundKey = 1;
    public String soundKey;

    // optional string jamKey = 2;
    public String jamKey;

    // optional string type = 3;
    public String type;

    public AdResources() {
      clear();
    }

    public AdResources clear() {
      soundKey = "";
      jamKey = "";
      type = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.soundKey.equals("")) {
        output.writeString(1, this.soundKey);
      }
      if (!this.jamKey.equals("")) {
        output.writeString(2, this.jamKey);
      }
      if (!this.type.equals("")) {
        output.writeString(3, this.type);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.soundKey.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.soundKey);
      }
      if (!this.jamKey.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.jamKey);
      }
      if (!this.type.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.type);
      }
      return size;
    }

    @Override
    public AdResources mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.soundKey = input.readString();
            break;
          }
          case 18: {
            this.jamKey = input.readString();
            break;
          }
          case 26: {
            this.type = input.readString();
            break;
          }
        }
      }
    }

    public static AdResources parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdResources(), data);
    }

    public static AdResources parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdResources().mergeFrom(input);
    }
  }

  public static final class UserRegistrationRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile UserRegistrationRequest[] _emptyArray;
    public static UserRegistrationRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UserRegistrationRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional string os = 2;
    public String os;

    // optional string idfa = 3;
    public String idfa;

    // optional string bundleId = 4;
    public String bundleId;

    // optional string bundleDisplayName = 5;
    public String bundleDisplayName;

    // optional string build = 6;
    public String build;

    // optional string version = 7;
    public String version;

    public UserRegistrationRequest() {
      clear();
    }

    public UserRegistrationRequest clear() {
      geo = "";
      os = "";
      idfa = "";
      bundleId = "";
      bundleDisplayName = "";
      build = "";
      version = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (!this.os.equals("")) {
        output.writeString(2, this.os);
      }
      if (!this.idfa.equals("")) {
        output.writeString(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        output.writeString(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        output.writeString(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        output.writeString(6, this.build);
      }
      if (!this.version.equals("")) {
        output.writeString(7, this.version);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (!this.os.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.os);
      }
      if (!this.idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.build);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.version);
      }
      return size;
    }

    @Override
    public UserRegistrationRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 18: {
            this.os = input.readString();
            break;
          }
          case 26: {
            this.idfa = input.readString();
            break;
          }
          case 34: {
            this.bundleId = input.readString();
            break;
          }
          case 42: {
            this.bundleDisplayName = input.readString();
            break;
          }
          case 50: {
            this.build = input.readString();
            break;
          }
          case 58: {
            this.version = input.readString();
            break;
          }
        }
      }
    }

    public static UserRegistrationRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UserRegistrationRequest(), data);
    }

    public static UserRegistrationRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UserRegistrationRequest().mergeFrom(input);
    }
  }

  public static final class UserRegistrationResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile UserRegistrationResponse[] _emptyArray;
    public static UserRegistrationResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UserRegistrationResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 timeStamp = 1;
    public long timeStamp;

    // optional string userId = 2;
    public String userId;

    public UserRegistrationResponse() {
      clear();
    }

    public UserRegistrationResponse clear() {
      timeStamp = 0L;
      userId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.timeStamp != 0L) {
        output.writeInt64(1, this.timeStamp);
      }
      if (!this.userId.equals("")) {
        output.writeString(2, this.userId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.timeStamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.timeStamp);
      }
      if (!this.userId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.userId);
      }
      return size;
    }

    @Override
    public UserRegistrationResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.timeStamp = input.readInt64();
            break;
          }
          case 18: {
            this.userId = input.readString();
            break;
          }
        }
      }
    }

    public static UserRegistrationResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UserRegistrationResponse(), data);
    }

    public static UserRegistrationResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UserRegistrationResponse().mergeFrom(input);
    }
  }

  public static final class AdShowStrategyRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdShowStrategyRequest[] _emptyArray;
    public static AdShowStrategyRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdShowStrategyRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 timeStamp = 1;
    public long timeStamp;

    // optional string geo = 2;
    public String geo;

    // optional string idfa = 3;
    public String idfa;

    // optional string bundleId = 4;
    public String bundleId;

    // optional string bundleDisplayName = 5;
    public String bundleDisplayName;

    // optional string build = 6;
    public String build;

    // optional string version = 7;
    public String version;

    public AdShowStrategyRequest() {
      clear();
    }

    public AdShowStrategyRequest clear() {
      timeStamp = 0L;
      geo = "";
      idfa = "";
      bundleId = "";
      bundleDisplayName = "";
      build = "";
      version = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.timeStamp != 0L) {
        output.writeInt64(1, this.timeStamp);
      }
      if (!this.geo.equals("")) {
        output.writeString(2, this.geo);
      }
      if (!this.idfa.equals("")) {
        output.writeString(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        output.writeString(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        output.writeString(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        output.writeString(6, this.build);
      }
      if (!this.version.equals("")) {
        output.writeString(7, this.version);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.timeStamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.timeStamp);
      }
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.geo);
      }
      if (!this.idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.build);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.version);
      }
      return size;
    }

    @Override
    public AdShowStrategyRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.timeStamp = input.readInt64();
            break;
          }
          case 18: {
            this.geo = input.readString();
            break;
          }
          case 26: {
            this.idfa = input.readString();
            break;
          }
          case 34: {
            this.bundleId = input.readString();
            break;
          }
          case 42: {
            this.bundleDisplayName = input.readString();
            break;
          }
          case 50: {
            this.build = input.readString();
            break;
          }
          case 58: {
            this.version = input.readString();
            break;
          }
        }
      }
    }

    public static AdShowStrategyRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdShowStrategyRequest(), data);
    }

    public static AdShowStrategyRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdShowStrategyRequest().mergeFrom(input);
    }
  }

  public static final class AdShowStrategyResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdShowStrategyResponse[] _emptyArray;
    public static AdShowStrategyResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdShowStrategyResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .AdStrategy adStrategyList = 1;
    public AdStrategy[] adStrategyList;

    // repeated .AdControl adControlList = 2;
    public AdControl[] adControlList;

    // repeated .AdClick adClickList = 3;
    public AdClick[] adClickList;

    // repeated .AdResources adResourcesList = 4;
    public AdResources[] adResourcesList;

    // optional int64 serverTime = 5;
    public long serverTime;

    public AdShowStrategyResponse() {
      clear();
    }

    public AdShowStrategyResponse clear() {
      adStrategyList = AdStrategy.emptyArray();
      adControlList = AdControl.emptyArray();
      adClickList = AdClick.emptyArray();
      adResourcesList = AdResources.emptyArray();
      serverTime = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.adStrategyList != null && this.adStrategyList.length > 0) {
        for (int i = 0; i < this.adStrategyList.length; i++) {
          AdStrategy element = this.adStrategyList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.adControlList != null && this.adControlList.length > 0) {
        for (int i = 0; i < this.adControlList.length; i++) {
          AdControl element = this.adControlList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.adClickList != null && this.adClickList.length > 0) {
        for (int i = 0; i < this.adClickList.length; i++) {
          AdClick element = this.adClickList[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      if (this.adResourcesList != null && this.adResourcesList.length > 0) {
        for (int i = 0; i < this.adResourcesList.length; i++) {
          AdResources element = this.adResourcesList[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      if (this.serverTime != 0L) {
        output.writeInt64(5, this.serverTime);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.adStrategyList != null && this.adStrategyList.length > 0) {
        for (int i = 0; i < this.adStrategyList.length; i++) {
          AdStrategy element = this.adStrategyList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.adControlList != null && this.adControlList.length > 0) {
        for (int i = 0; i < this.adControlList.length; i++) {
          AdControl element = this.adControlList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.adClickList != null && this.adClickList.length > 0) {
        for (int i = 0; i < this.adClickList.length; i++) {
          AdClick element = this.adClickList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      if (this.adResourcesList != null && this.adResourcesList.length > 0) {
        for (int i = 0; i < this.adResourcesList.length; i++) {
          AdResources element = this.adResourcesList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      if (this.serverTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(5, this.serverTime);
      }
      return size;
    }

    @Override
    public AdShowStrategyResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.adStrategyList == null ? 0 : this.adStrategyList.length;
            AdStrategy[] newArray =
                new AdStrategy[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adStrategyList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new AdStrategy();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new AdStrategy();
            input.readMessage(newArray[i]);
            this.adStrategyList = newArray;
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.adControlList == null ? 0 : this.adControlList.length;
            AdControl[] newArray =
                new AdControl[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adControlList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new AdControl();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new AdControl();
            input.readMessage(newArray[i]);
            this.adControlList = newArray;
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.adClickList == null ? 0 : this.adClickList.length;
            AdClick[] newArray =
                new AdClick[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adClickList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new AdClick();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new AdClick();
            input.readMessage(newArray[i]);
            this.adClickList = newArray;
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.adResourcesList == null ? 0 : this.adResourcesList.length;
            AdResources[] newArray =
                new AdResources[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adResourcesList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new AdResources();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new AdResources();
            input.readMessage(newArray[i]);
            this.adResourcesList = newArray;
            break;
          }
          case 40: {
            this.serverTime = input.readInt64();
            break;
          }
        }
      }
    }

    public static AdShowStrategyResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdShowStrategyResponse(), data);
    }

    public static AdShowStrategyResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdShowStrategyResponse().mergeFrom(input);
    }
  }

  public static final class DataStatisticsRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile DataStatisticsRequest[] _emptyArray;
    public static DataStatisticsRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new DataStatisticsRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional string bundleId = 2;
    public String bundleId;

    // optional string bundleDisplayName = 3;
    public String bundleDisplayName;

    // optional string build = 4;
    public String build;

    // optional string version = 5;
    public String version;

    // optional string networkType = 6;
    public String networkType;

    // optional string idfa = 7;
    public String idfa;

    // optional int32 eventNumber = 8;
    public int eventNumber;

    // repeated .eventApplicationStartup applicationStartupList = 9;
    public eventApplicationStartup[] applicationStartupList;

    // repeated .eventPageSwitching pageSwitchingList = 10;
    public eventPageSwitching[] pageSwitchingList;

    // repeated .eventAdRequest adRequestList = 11;
    public eventAdRequest[] adRequestList;

    // repeated .eventAdShow adShowList = 12;
    public eventAdShow[] adShowList;

    // repeated .eventAdClick adClickList = 13;
    public eventAdClick[] adClickList;

    // optional int64 timeStamp = 14;
    public long timeStamp;

    public DataStatisticsRequest() {
      clear();
    }

    public DataStatisticsRequest clear() {
      geo = "";
      bundleId = "";
      bundleDisplayName = "";
      build = "";
      version = "";
      networkType = "";
      idfa = "";
      eventNumber = 0;
      applicationStartupList = eventApplicationStartup.emptyArray();
      pageSwitchingList = eventPageSwitching.emptyArray();
      adRequestList = eventAdRequest.emptyArray();
      adShowList = eventAdShow.emptyArray();
      adClickList = eventAdClick.emptyArray();
      timeStamp = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (!this.bundleId.equals("")) {
        output.writeString(2, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        output.writeString(3, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        output.writeString(4, this.build);
      }
      if (!this.version.equals("")) {
        output.writeString(5, this.version);
      }
      if (!this.networkType.equals("")) {
        output.writeString(6, this.networkType);
      }
      if (!this.idfa.equals("")) {
        output.writeString(7, this.idfa);
      }
      if (this.eventNumber != 0) {
        output.writeInt32(8, this.eventNumber);
      }
      if (this.applicationStartupList != null && this.applicationStartupList.length > 0) {
        for (int i = 0; i < this.applicationStartupList.length; i++) {
          eventApplicationStartup element = this.applicationStartupList[i];
          if (element != null) {
            output.writeMessage(9, element);
          }
        }
      }
      if (this.pageSwitchingList != null && this.pageSwitchingList.length > 0) {
        for (int i = 0; i < this.pageSwitchingList.length; i++) {
          eventPageSwitching element = this.pageSwitchingList[i];
          if (element != null) {
            output.writeMessage(10, element);
          }
        }
      }
      if (this.adRequestList != null && this.adRequestList.length > 0) {
        for (int i = 0; i < this.adRequestList.length; i++) {
          eventAdRequest element = this.adRequestList[i];
          if (element != null) {
            output.writeMessage(11, element);
          }
        }
      }
      if (this.adShowList != null && this.adShowList.length > 0) {
        for (int i = 0; i < this.adShowList.length; i++) {
          eventAdShow element = this.adShowList[i];
          if (element != null) {
            output.writeMessage(12, element);
          }
        }
      }
      if (this.adClickList != null && this.adClickList.length > 0) {
        for (int i = 0; i < this.adClickList.length; i++) {
          eventAdClick element = this.adClickList[i];
          if (element != null) {
            output.writeMessage(13, element);
          }
        }
      }
      if (this.timeStamp != 0L) {
        output.writeInt64(14, this.timeStamp);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.build);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.version);
      }
      if (!this.networkType.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.networkType);
      }
      if (!this.idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.idfa);
      }
      if (this.eventNumber != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(8, this.eventNumber);
      }
      if (this.applicationStartupList != null && this.applicationStartupList.length > 0) {
        for (int i = 0; i < this.applicationStartupList.length; i++) {
          eventApplicationStartup element = this.applicationStartupList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(9, element);
          }
        }
      }
      if (this.pageSwitchingList != null && this.pageSwitchingList.length > 0) {
        for (int i = 0; i < this.pageSwitchingList.length; i++) {
          eventPageSwitching element = this.pageSwitchingList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(10, element);
          }
        }
      }
      if (this.adRequestList != null && this.adRequestList.length > 0) {
        for (int i = 0; i < this.adRequestList.length; i++) {
          eventAdRequest element = this.adRequestList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(11, element);
          }
        }
      }
      if (this.adShowList != null && this.adShowList.length > 0) {
        for (int i = 0; i < this.adShowList.length; i++) {
          eventAdShow element = this.adShowList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(12, element);
          }
        }
      }
      if (this.adClickList != null && this.adClickList.length > 0) {
        for (int i = 0; i < this.adClickList.length; i++) {
          eventAdClick element = this.adClickList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(13, element);
          }
        }
      }
      if (this.timeStamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(14, this.timeStamp);
      }
      return size;
    }

    @Override
    public DataStatisticsRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 18: {
            this.bundleId = input.readString();
            break;
          }
          case 26: {
            this.bundleDisplayName = input.readString();
            break;
          }
          case 34: {
            this.build = input.readString();
            break;
          }
          case 42: {
            this.version = input.readString();
            break;
          }
          case 50: {
            this.networkType = input.readString();
            break;
          }
          case 58: {
            this.idfa = input.readString();
            break;
          }
          case 64: {
            this.eventNumber = input.readInt32();
            break;
          }
          case 74: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 74);
            int i = this.applicationStartupList == null ? 0 : this.applicationStartupList.length;
            eventApplicationStartup[] newArray =
                new eventApplicationStartup[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.applicationStartupList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new eventApplicationStartup();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new eventApplicationStartup();
            input.readMessage(newArray[i]);
            this.applicationStartupList = newArray;
            break;
          }
          case 82: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 82);
            int i = this.pageSwitchingList == null ? 0 : this.pageSwitchingList.length;
            eventPageSwitching[] newArray =
                new eventPageSwitching[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.pageSwitchingList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new eventPageSwitching();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new eventPageSwitching();
            input.readMessage(newArray[i]);
            this.pageSwitchingList = newArray;
            break;
          }
          case 90: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 90);
            int i = this.adRequestList == null ? 0 : this.adRequestList.length;
            eventAdRequest[] newArray =
                new eventAdRequest[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adRequestList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new eventAdRequest();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new eventAdRequest();
            input.readMessage(newArray[i]);
            this.adRequestList = newArray;
            break;
          }
          case 98: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 98);
            int i = this.adShowList == null ? 0 : this.adShowList.length;
            eventAdShow[] newArray =
                new eventAdShow[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adShowList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new eventAdShow();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new eventAdShow();
            input.readMessage(newArray[i]);
            this.adShowList = newArray;
            break;
          }
          case 106: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 106);
            int i = this.adClickList == null ? 0 : this.adClickList.length;
            eventAdClick[] newArray =
                new eventAdClick[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.adClickList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new eventAdClick();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new eventAdClick();
            input.readMessage(newArray[i]);
            this.adClickList = newArray;
            break;
          }
          case 112: {
            this.timeStamp = input.readInt64();
            break;
          }
        }
      }
    }

    public static DataStatisticsRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new DataStatisticsRequest(), data);
    }

    public static DataStatisticsRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new DataStatisticsRequest().mergeFrom(input);
    }
  }

  public static final class DataStatisticsResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile DataStatisticsResponse[] _emptyArray;
    public static DataStatisticsResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new DataStatisticsResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string success = 1;
    public String success;

    // optional bool status = 2;
    public boolean status;

    public DataStatisticsResponse() {
      clear();
    }

    public DataStatisticsResponse clear() {
      success = "";
      status = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.success.equals("")) {
        output.writeString(1, this.success);
      }
      if (this.status != false) {
        output.writeBool(2, this.status);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.success.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.success);
      }
      if (this.status != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.status);
      }
      return size;
    }

    @Override
    public DataStatisticsResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.success = input.readString();
            break;
          }
          case 16: {
            this.status = input.readBool();
            break;
          }
        }
      }
    }

    public static DataStatisticsResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new DataStatisticsResponse(), data);
    }

    public static DataStatisticsResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new DataStatisticsResponse().mergeFrom(input);
    }
  }

  public static final class eventApplicationStartup extends
      com.google.protobuf.nano.MessageNano {

    private static volatile eventApplicationStartup[] _emptyArray;
    public static eventApplicationStartup[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new eventApplicationStartup[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional int64 timeStartup = 2;
    public long timeStartup;

    public eventApplicationStartup() {
      clear();
    }

    public eventApplicationStartup clear() {
      geo = "";
      timeStartup = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (this.timeStartup != 0L) {
        output.writeInt64(2, this.timeStartup);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (this.timeStartup != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.timeStartup);
      }
      return size;
    }

    @Override
    public eventApplicationStartup mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 16: {
            this.timeStartup = input.readInt64();
            break;
          }
        }
      }
    }

    public static eventApplicationStartup parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new eventApplicationStartup(), data);
    }

    public static eventApplicationStartup parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new eventApplicationStartup().mergeFrom(input);
    }
  }

  public static final class eventPageSwitching extends
      com.google.protobuf.nano.MessageNano {

    private static volatile eventPageSwitching[] _emptyArray;
    public static eventPageSwitching[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new eventPageSwitching[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string pageName = 1;
    public String pageName;

    // optional string geo = 2;
    public String geo;

    // optional int64 timeSwitching = 3;
    public long timeSwitching;

    public eventPageSwitching() {
      clear();
    }

    public eventPageSwitching clear() {
      pageName = "";
      geo = "";
      timeSwitching = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.pageName.equals("")) {
        output.writeString(1, this.pageName);
      }
      if (!this.geo.equals("")) {
        output.writeString(2, this.geo);
      }
      if (this.timeSwitching != 0L) {
        output.writeInt64(3, this.timeSwitching);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.pageName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.pageName);
      }
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.geo);
      }
      if (this.timeSwitching != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.timeSwitching);
      }
      return size;
    }

    @Override
    public eventPageSwitching mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.pageName = input.readString();
            break;
          }
          case 18: {
            this.geo = input.readString();
            break;
          }
          case 24: {
            this.timeSwitching = input.readInt64();
            break;
          }
        }
      }
    }

    public static eventPageSwitching parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new eventPageSwitching(), data);
    }

    public static eventPageSwitching parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new eventPageSwitching().mergeFrom(input);
    }
  }

  public static final class eventAdRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile eventAdRequest[] _emptyArray;
    public static eventAdRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new eventAdRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional int64 timeRequest = 2;
    public long timeRequest;

    // optional int32 adPositionNumber = 3;
    public int adPositionNumber;

    // optional int32 adType = 4;
    public int adType;

    public eventAdRequest() {
      clear();
    }

    public eventAdRequest clear() {
      geo = "";
      timeRequest = 0L;
      adPositionNumber = 0;
      adType = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (this.timeRequest != 0L) {
        output.writeInt64(2, this.timeRequest);
      }
      if (this.adPositionNumber != 0) {
        output.writeInt32(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        output.writeInt32(4, this.adType);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (this.timeRequest != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.timeRequest);
      }
      if (this.adPositionNumber != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.adType);
      }
      return size;
    }

    @Override
    public eventAdRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 16: {
            this.timeRequest = input.readInt64();
            break;
          }
          case 24: {
            this.adPositionNumber = input.readInt32();
            break;
          }
          case 32: {
            this.adType = input.readInt32();
            break;
          }
        }
      }
    }

    public static eventAdRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new eventAdRequest(), data);
    }

    public static eventAdRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new eventAdRequest().mergeFrom(input);
    }
  }

  public static final class eventAdShow extends
      com.google.protobuf.nano.MessageNano {

    private static volatile eventAdShow[] _emptyArray;
    public static eventAdShow[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new eventAdShow[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional int64 timeShow = 2;
    public long timeShow;

    // optional int32 adPositionNumber = 3;
    public int adPositionNumber;

    // optional int32 adType = 4;
    public int adType;

    public eventAdShow() {
      clear();
    }

    public eventAdShow clear() {
      geo = "";
      timeShow = 0L;
      adPositionNumber = 0;
      adType = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (this.timeShow != 0L) {
        output.writeInt64(2, this.timeShow);
      }
      if (this.adPositionNumber != 0) {
        output.writeInt32(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        output.writeInt32(4, this.adType);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (this.timeShow != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.timeShow);
      }
      if (this.adPositionNumber != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.adType);
      }
      return size;
    }

    @Override
    public eventAdShow mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 16: {
            this.timeShow = input.readInt64();
            break;
          }
          case 24: {
            this.adPositionNumber = input.readInt32();
            break;
          }
          case 32: {
            this.adType = input.readInt32();
            break;
          }
        }
      }
    }

    public static eventAdShow parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new eventAdShow(), data);
    }

    public static eventAdShow parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new eventAdShow().mergeFrom(input);
    }
  }

  public static final class eventAdClick extends
      com.google.protobuf.nano.MessageNano {

    private static volatile eventAdClick[] _emptyArray;
    public static eventAdClick[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new eventAdClick[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string geo = 1;
    public String geo;

    // optional int64 timeClick = 2;
    public long timeClick;

    // optional int32 adPositionNumber = 3;
    public int adPositionNumber;

    // optional int32 adType = 4;
    public int adType;

    public eventAdClick() {
      clear();
    }

    public eventAdClick clear() {
      geo = "";
      timeClick = 0L;
      adPositionNumber = 0;
      adType = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.geo.equals("")) {
        output.writeString(1, this.geo);
      }
      if (this.timeClick != 0L) {
        output.writeInt64(2, this.timeClick);
      }
      if (this.adPositionNumber != 0) {
        output.writeInt32(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        output.writeInt32(4, this.adType);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.geo);
      }
      if (this.timeClick != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.timeClick);
      }
      if (this.adPositionNumber != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.adPositionNumber);
      }
      if (this.adType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.adType);
      }
      return size;
    }

    @Override
    public eventAdClick mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.geo = input.readString();
            break;
          }
          case 16: {
            this.timeClick = input.readInt64();
            break;
          }
          case 24: {
            this.adPositionNumber = input.readInt32();
            break;
          }
          case 32: {
            this.adType = input.readInt32();
            break;
          }
        }
      }
    }

    public static eventAdClick parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new eventAdClick(), data);
    }

    public static eventAdClick parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new eventAdClick().mergeFrom(input);
    }
  }

  public static final class AdSendPushRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdSendPushRequest[] _emptyArray;
    public static AdSendPushRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdSendPushRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 timeStamp = 1;
    public long timeStamp;

    // optional string geo = 2;
    public String geo;

    // optional string idfa = 3;
    public String idfa;

    // optional string bundleId = 4;
    public String bundleId;

    // optional string bundleDisplayName = 5;
    public String bundleDisplayName;

    // optional string build = 6;
    public String build;

    // optional string version = 7;
    public String version;

    // optional string deviceToken = 8;
    public String deviceToken;

    // optional int32 isUninstall = 9;
    public int isUninstall;

    public AdSendPushRequest() {
      clear();
    }

    public AdSendPushRequest clear() {
      timeStamp = 0L;
      geo = "";
      idfa = "";
      bundleId = "";
      bundleDisplayName = "";
      build = "";
      version = "";
      deviceToken = "";
      isUninstall = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.timeStamp != 0L) {
        output.writeInt64(1, this.timeStamp);
      }
      if (!this.geo.equals("")) {
        output.writeString(2, this.geo);
      }
      if (!this.idfa.equals("")) {
        output.writeString(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        output.writeString(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        output.writeString(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        output.writeString(6, this.build);
      }
      if (!this.version.equals("")) {
        output.writeString(7, this.version);
      }
      if (!this.deviceToken.equals("")) {
        output.writeString(8, this.deviceToken);
      }
      if (this.isUninstall != 0) {
        output.writeInt32(9, this.isUninstall);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.timeStamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.timeStamp);
      }
      if (!this.geo.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.geo);
      }
      if (!this.idfa.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.idfa);
      }
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.bundleId);
      }
      if (!this.bundleDisplayName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.bundleDisplayName);
      }
      if (!this.build.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.build);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.version);
      }
      if (!this.deviceToken.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.deviceToken);
      }
      if (this.isUninstall != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.isUninstall);
      }
      return size;
    }

    @Override
    public AdSendPushRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.timeStamp = input.readInt64();
            break;
          }
          case 18: {
            this.geo = input.readString();
            break;
          }
          case 26: {
            this.idfa = input.readString();
            break;
          }
          case 34: {
            this.bundleId = input.readString();
            break;
          }
          case 42: {
            this.bundleDisplayName = input.readString();
            break;
          }
          case 50: {
            this.build = input.readString();
            break;
          }
          case 58: {
            this.version = input.readString();
            break;
          }
          case 66: {
            this.deviceToken = input.readString();
            break;
          }
          case 72: {
            this.isUninstall = input.readInt32();
            break;
          }
        }
      }
    }

    public static AdSendPushRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdSendPushRequest(), data);
    }

    public static AdSendPushRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdSendPushRequest().mergeFrom(input);
    }
  }

  public static final class AdSendPushResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AdSendPushResponse[] _emptyArray;
    public static AdSendPushResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdSendPushResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 sendTime = 1;
    public long sendTime;

    // optional string success = 2;
    public String success;

    public AdSendPushResponse() {
      clear();
    }

    public AdSendPushResponse clear() {
      sendTime = 0L;
      success = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.sendTime != 0L) {
        output.writeInt64(1, this.sendTime);
      }
      if (!this.success.equals("")) {
        output.writeString(2, this.success);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.sendTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.sendTime);
      }
      if (!this.success.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.success);
      }
      return size;
    }

    @Override
    public AdSendPushResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.sendTime = input.readInt64();
            break;
          }
          case 18: {
            this.success = input.readString();
            break;
          }
        }
      }
    }

    public static AdSendPushResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AdSendPushResponse(), data);
    }

    public static AdSendPushResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdSendPushResponse().mergeFrom(input);
    }
  }

  public static final class Apps extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Apps[] _emptyArray;
    public static Apps[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Apps[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string bundleId = 1;
    public String bundleId;

    // optional string version = 2;
    public String version;

    // optional string url = 3;
    public String url;

    // optional string icon = 4;
    public String icon;

    public Apps() {
      clear();
    }

    public Apps clear() {
      bundleId = "";
      version = "";
      url = "";
      icon = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.bundleId.equals("")) {
        output.writeString(1, this.bundleId);
      }
      if (!this.version.equals("")) {
        output.writeString(2, this.version);
      }
      if (!this.url.equals("")) {
        output.writeString(3, this.url);
      }
      if (!this.icon.equals("")) {
        output.writeString(4, this.icon);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.bundleId);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.version);
      }
      if (!this.url.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.url);
      }
      if (!this.icon.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.icon);
      }
      return size;
    }

    @Override
    public Apps mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.bundleId = input.readString();
            break;
          }
          case 18: {
            this.version = input.readString();
            break;
          }
          case 26: {
            this.url = input.readString();
            break;
          }
          case 34: {
            this.icon = input.readString();
            break;
          }
        }
      }
    }

    public static Apps parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Apps(), data);
    }

    public static Apps parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Apps().mergeFrom(input);
    }
  }

  public static final class AppsRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AppsRequest[] _emptyArray;
    public static AppsRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AppsRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string bundleId = 1;
    public String bundleId;

    // optional string version = 2;
    public String version;

    public AppsRequest() {
      clear();
    }

    public AppsRequest clear() {
      bundleId = "";
      version = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.bundleId.equals("")) {
        output.writeString(1, this.bundleId);
      }
      if (!this.version.equals("")) {
        output.writeString(2, this.version);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.bundleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.bundleId);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.version);
      }
      return size;
    }

    @Override
    public AppsRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.bundleId = input.readString();
            break;
          }
          case 18: {
            this.version = input.readString();
            break;
          }
        }
      }
    }

    public static AppsRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AppsRequest(), data);
    }

    public static AppsRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AppsRequest().mergeFrom(input);
    }
  }

  public static final class AppsResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AppsResponse[] _emptyArray;
    public static AppsResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AppsResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .Apps AppsList = 1;
    public Apps[] appsList;

    // optional string status = 2;
    public String status;

    // optional int64 time = 3;
    public long time;

    public AppsResponse() {
      clear();
    }

    public AppsResponse clear() {
      appsList = Apps.emptyArray();
      status = "";
      time = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.appsList != null && this.appsList.length > 0) {
        for (int i = 0; i < this.appsList.length; i++) {
          Apps element = this.appsList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (!this.status.equals("")) {
        output.writeString(2, this.status);
      }
      if (this.time != 0L) {
        output.writeInt64(3, this.time);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.appsList != null && this.appsList.length > 0) {
        for (int i = 0; i < this.appsList.length; i++) {
          Apps element = this.appsList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (!this.status.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.status);
      }
      if (this.time != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.time);
      }
      return size;
    }

    @Override
    public AppsResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.appsList == null ? 0 : this.appsList.length;
            Apps[] newArray =
                new Apps[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.appsList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new Apps();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new Apps();
            input.readMessage(newArray[i]);
            this.appsList = newArray;
            break;
          }
          case 18: {
            this.status = input.readString();
            break;
          }
          case 24: {
            this.time = input.readInt64();
            break;
          }
        }
      }
    }

    public static AppsResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AppsResponse(), data);
    }

    public static AppsResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AppsResponse().mergeFrom(input);
    }
  }
}
